from pydantic import BaseModel

MANDATORY_DISCLAIMER = (
    "This report is generated by an AI-assisted analysis system and is intended "
    "for use by licensed insurance underwriters only. The information contained "
    "herein is based solely on the loss run data provided and does not constitute "
    "a coverage opinion, underwriting decision, or legal advice. All figures should "
    "be independently verified against source documents prior to any underwriting action."
)


class UnderwriterSummary(BaseModel):
    job_id: str
    executive_summary: str = ""
    year_by_year: str = ""
    large_loss_detail: str = ""
    open_claim_status: str = ""
    red_flag_disclosure: str = ""
    risk_management_observations: str = ""
    disclaimer: str = MANDATORY_DISCLAIMER
